commit by Valeb0nd
migs911/hyperbaton_homework pull request #14
Opened 2021-10-04 18:46 UTC by valeb0nd

- переименовала файл template.txt,
- добавила commit_sha в template.txt,
- удалила файл с подсказками.

2021-10-05 21:02 UTC, migs911 requested changes

2021-10-05 21:02 UTC, migs911 commented on homework/valeb0nd.txt
> +<5e3669747339abb9bbb29b9002e6b29f1b154313>
Угловые скобки надо убрать)
Таким образом просто часто помечают переменные — т.е. место, куда надо что-то подставить.

2021-10-06 06:49 UTC, valeb0nd commented on homework/valeb0nd.txt
> +<5e3669747339abb9bbb29b9002e6b29f1b154313>
Привет! Спасибо, скобки убрала :) 
Закрываю тред)

2021-10-07 10:48 UTC, migs911 approved these changes

2021-10-07 10:48 UTC, merged